apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: homebrew-tap
  description: "Governance definition for homebrew-tap"
  annotations:
    app-mindburn-web.org/project-tier: service
spec:
  type: service
  lifecycle: production
  owner: architecture-platform
